### ISSUE TITLE
Restore /admin/structure path access and provide link from Manage menu

### ISSUE THREAD

**Issue by ba66e77** [acquia/reservoir#21]
In the [ReservoirUIRouteSubscriber](https://github.com/acquia/reservoir/blob/8.x-1.x/modules/reservoir_ui/src/Routing/ReservoirUiRouteSubscriber.php#L22), access to the system.admin_structure route is forced to FALSE.  While this in some ways simplifies the UI by removing Display Modes and other aspects which are meaningless in a headless system, it has the (presumably) unintended side effect of blocking access to the configuration screens for taxonomy and for input formats, both of which are still meaningful for headless systems.

**Comment by wimleers** [comment]
Many (most?) headless systems don't really need to make major changes to text format & text editor configuration. Also, they're very much Drupalisms. For now, Reservoir is making the choice to _not_ expose their configuration.

Creating additional vocabularies is _more_ likely to be useful/relevant/necessary for headless systems. But here too, Reservoir is _for now_ making the choice to not expose that. I believe that the "Tags" folksonomy is "good enough" for many use cases. Even more so because in a headless system, you might as well create additional content models (`node_type`s in Drupal lingo) and then reference content of those content models instead. Exposing taxonomy vocabularies means you can have "two kinds" of content models. And both are fieldable. For many intents & purposes, they just have different internals, and have different UIs. That's … very confusing for non-Drupalists.

So, until this is requested many times, I'm going to have to disagree for the sake of making Reservoir accessible to non-Drupalists.

I hope that made sense! Happy to continue this conversation. This is not a "definitive no". This is a "no for now".

**Comment by ba66e77** [comment]
When I bend my Drupalist brain around the idea that this isn't supposed to be Drupal-y, then the UI choices made make sense.

Having said that, as a Drupalist who needs to build headless systems, I'd like to find a way I and others like me can use Reservoir as more than a source of information from which to reverse engineer all the headless goodness y'all have worked out. A way I can have Reservoir AND my drupal-isms; maybe a sub-module of reservoir_ui that restores some of things like taxonomy.  Is that something you and the project would be willing to consider?

**Comment by wimleers** [comment]
That is an excellent question!

That sounds like a "I'm a Drupalist" checkbox during the installer, to install the `reservoir_ui_drupalist` module?

I think this is the sort of thing that needs a long-running, thoughtful, balanced discussion :)

**Comment by ba66e77** [comment]
Alright.  We can call this "wont fix" then.  I've started #22 as a place for that longer discussion.

Thanks @wimleers

**Comment by wimleers** [comment]
I don't understand why you closed this and created a new issue, now we have to just repeat/quote some things said here. But it's fine :)
