### ISSUE TITLE
Cannot create clients

### ISSUE THREAD

**Issue by damontgomery** [acquia/reservoir#9]
Version: Alpha 1

If I try to create a client, the Save button is grayed out and there is a notice, `Create a role for every logical group of permissions you want to assign to a client.` I'm not sure if they are related.

![add_client___well](https://user-images.githubusercontent.com/397902/27344665-bc5d3354-55ac-11e7-933e-8fddcae0a691.jpg)

**Comment by damontgomery** [comment]
OK, I found that if I follow this pattern, I can create a new App:
- Create a new content type (optional)
- Create a new role
- Assign that role the permission to edit the content type (optional)
- Create a new client (assign scope to the new role)

The message above seems to indicate that, but it's not super clear that you NEED to create a new role since the whole site seems set up as a demo. Maybe create a demo role to avoid this or update the tutorial / error?

I'll close this for now.

**Comment by tedbow** [comment]
Re-opening to figure out if we need better help text.

**Comment by wimleers** [comment]
@damontgomery Thank you for taking the time to report your confusion! That's exactly the sort of information we need :)

You list four steps:
> - Create a new content type (optional)
> - Create a new role
> - Assign that role the permission to edit the content type (optional)
> - Create a new client (assign scope to the new role)

You definitely don't need that first step. You also marked it as optional. The third step you don't need.

The "Save" button you point to in the screen is intentionally disabled, and that's why there's that big red warning at the top.

The site is indeed set up as a demo, but in the default demo, the default Client has _no_ roles. So the demo client is set up in a way that you cannot set up your own clients. That's indeed… confusing.

So how about I add a "CLIENT: own articles" role that allows creating articles and editing one's own articles? Then it looks like this by default:
![screen shot 2017-06-21 at 10 12 59](https://user-images.githubusercontent.com/14240/27373904-42643cbe-566a-11e7-8700-3745e540a4f2.png)

Adding PR …

**Comment by wimleers** [comment]
Fixed by #10.
